apiVersion: ops.example.com/v1
kind: GPUHealthPolicy
metadata:
  labels:
    app.kubernetes.io/name: gpu-ops-operator
    app.kubernetes.io/managed-by: kustomize
  name: gpuhealthpolicy-sample
spec:
  # TODO(user): Add fields here
