---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ops.example.com
  resources:
  - gpuhealthpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.example.com
  resources:
  - gpuhealthpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - ops.example.com
  resources:
  - gpuhealthpolicies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - evictions
  verbs:
  - create
